### ISSUE TITLE
Server got error after open on browser

### ISSUE THREAD

**Issue by stefanospindola** [bhoov/exbert#23]
Hi, I run 'python server/main.py' and I got this error after open the server address:

```
Traceback (most recent call last):
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/uvicorn/protocols/http/h11_impl.py", line 369, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 59, in _call_
    return await self.app(scope, receive, send)
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/fastapi/applications.py", line 199, in _call_
    await super()._call_(scope, receive, send)
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/starlette/applications.py", line 112, in _call_
    await self.middleware_stack(scope, receive, send)
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in _call_
    raise exc from None
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in _call_
    await self.app(scope, receive, _send)
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/starlette/middleware/cors.py", line 78, in _call_
    await self.app(scope, receive, send)
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in _call_
    raise exc from None
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in _call_
    await self.app(scope, receive, sender)
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/starlette/routing.py", line 580, in _call_
    await route.handle(scope, receive, send)
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/fastapi/routing.py", line 202, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/stefano-spindola/Documentos/rag-test/exbert/server/main.py", line 140, in get_model_details
    deets = aconf.from_pretrained(model)
  File "/home/stefano-spindola/Documentos/rag-test/exbert/server/main.py", line 93, in from_pretrained
    return get_details(model_name)
  File "/home/stefano-spindola/Documentos/rag-test/exbert/server/transformer_details.py", line 31, in get_details
    return ModelDetails(mname)
  File "/home/stefano-spindola/Documentos/rag-test/exbert/server/transformer_details.py", line 44, in _init_
    self.model, self.aligner = get_model_tok(self.mname)
  File "/home/stefano-spindola/Documentos/rag-test/exbert/server/utils/f.py", line 74, in helper
    memo[x] = f(*x)
  File "/home/stefano-spindola/Documentos/rag-test/exbert/server/transformer_details.py", line 36, in get_model_tok
    tok = auto_aligner(mname, config=conf)
  File "/home/stefano-spindola/Documentos/rag-test/exbert/server/spacyface/spacyface/aligner.py", line 263, in auto_aligner
    return MakeAligner(tok_class, english).from_pretrained(pretrained_name_or_path, config=config)
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 911, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/stefano-spindola/anaconda3/envs/exbert/lib/python3.7/site-packages/transformers/tokenization_utils.py", line 1065, in _from_pretrained
    "Unable to load vocabulary from file. "
OSError: Unable to load vocabulary from file. Please check that the provided vocabulary is accessible and not corrupted.
```

How could I fix this?

**Comment by bhoov** [comment]
Weird, I haven't seen this one before. It seems like the Transformers library is having trouble loading the vocabulary for the tokenizer corresponding to the default "bert-base-cased" model.

1. What version of Transformers are you using?
2. Since developing this package, the default cache Huggingface directory has changed. Can you check what contents are in your `~/.cache/huggingface`? Perhaps deleting some parts of that folder that are corrupted could help
